version: "3.8"

services:
  mqtt:
    image: eclipse-mosquitto:2.0
    restart: unless-stopped
    volumes:
      - ./broker/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - ./broker/passwd:/mosquitto/config/passwd:ro
      - mosquitto-data:/mosquitto/data
    ports:
      - "1883:1883"

  mongo:
    image: mongo:6.0
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  backend:
    build: ./backend
    restart: unless-stopped
    env_file:
      - ./backend/.env.example
    environment:
      - MONGO_URI=mongodb://mongo:27017/iot
      - MQTT_URL=mqtt://mqtt:1883
    ports:
      - "3000:3000"
    depends_on:
      - mqtt
      - mongo

  frontend:
    build: ./frontend
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  mongo-data:
  mosquitto-data:
